import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { useTypingEffect } from '../hooks/useTypingEffect';

const SummaryResult = ({ text }) => {
  const [copied, setCopied] = useState(false);
  const displayedText = useTypingEffect(text, 15);
  const isTyping = displayedText.length < text.length;

  const handleCopy = () => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (!text) return null;

  return (
    <div className="glass-card fade-in-slide-up" style={{
      marginTop: '2rem',
      borderTop: '2px solid var(--accent-gold)',
      padding: '24px',
      position: 'relative',
      zIndex: 10,
      width: '100%'
    }}>
      {/* Header Row */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
        paddingBottom: '16px',
        borderBottom: '1px solid var(--glass-border)'
      }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: '12px' }}>
          <h3 style={{ 
            fontFamily: "'Space Grotesk', sans-serif", 
            fontWeight: 600, 
            fontSize: '1.2rem', 
            color: 'var(--text-primary)',
            margin: 0
          }}>
            Summary
          </h3>
          <span style={{ 
            fontFamily: "'Space Grotesk', sans-serif", 
            fontWeight: 300, 
            fontSize: '0.8rem', 
            color: 'var(--text-muted)'
          }}>
            Generated by Gemini AI
          </span>
        </div>
        
        {/* Copy Button */}
        <button 
          onClick={handleCopy}
          disabled={isTyping}
          style={{
            background: 'rgba(255,255,255,0.03)',
            border: '1px solid var(--glass-border)',
            borderRadius: '8px',
            color: copied ? 'var(--accent-gold)' : 'var(--text-secondary)',
            cursor: isTyping ? 'not-allowed' : 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '8px',
            transition: 'all 0.2s ease',
            opacity: isTyping ? 0.5 : 1
          }}
          title="Copy to clipboard"
          onMouseOver={(e) => {
            if (!isTyping && !copied) {
              e.currentTarget.style.color = 'var(--text-primary)';
              e.currentTarget.style.background = 'rgba(255,255,255,0.08)';
            }
          }}
          onMouseOut={(e) => {
            if (!isTyping && !copied) {
              e.currentTarget.style.color = 'var(--text-secondary)';
              e.currentTarget.style.background = 'rgba(255,255,255,0.03)';
            }
          }}
        >
          {copied ? <Check size={18} /> : <Copy size={18} />}
        </button>
      </div>

      {/* Body: Typing Effect Content */}
      <div style={{
        fontFamily: "'Space Grotesk', sans-serif", 
        fontWeight: 400, 
        color: 'var(--text-secondary)',
        fontSize: '1rem',
        lineHeight: 1.8,
        whiteSpace: 'pre-wrap'
      }}>
        {displayedText}
        {isTyping && <span className="cursor-blink" style={{ color: 'var(--accent-gold)', marginLeft: '2px' }}>|</span>}
      </div>

      {/* Footer Info */}
      <div style={{
        marginTop: '24px',
        textAlign: 'right',
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        fontFamily: "'Space Grotesk', sans-serif", 
      }}>
        {!isTyping && `${text.length} characters • ${text.split(/\s+/).filter(Boolean).length} words`}
      </div>
    </div>
  );
};

export default SummaryResult;
